<?php

function greeting_theme() {
  $theme['greeting_page'] = [
    'variables' => ['from' => NULL, 'to' => NULL, 'count' => NULL],
    'template' => 'greeting_page',
  ];
  $theme['greeting_node'] = [
    'variables' => ['body' => NULL, 'name' => NULL, 'tags' => NULL],
    'template' => 'greeting_node',
  ];
  $theme['greeting_status_block'] = [
    'variables' => ['enabled' => NULL, 'to' => NULL, 'greeting' => NULL],
    'template' => 'greeting_status_block',
  ];

  return $theme;
}
